Update buildlive for new initscripts with functions. Also PKGBUILDs. Important: note that only the xmini profile has been updated, the others won't work yet!

diff --git a/trunk/larch/buildlive b/trunk/larch/buildlive
--- a/trunk/larch/buildlive
+++ b/trunk/larch/buildlive
@@ -19,7 +19,7 @@
 #    51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 #
 #----------------------------------------------------------------------------
-# 2008.04.04
+# 2008.04.27
 
 # Location for the CD image
 CDDATA="${LARCHBUILD}/cd"
@@ -74,6 +74,10 @@ mklive ()
     if ! ${chrootx}grep /squashfs.ko \
             /lib/modules/${KVERSION}/modules.dep &>/dev/null; then
         echo "ERROR: No squashfs module found"
+        fail=1
+    fi
+    if ! [ -f "${INSTLDIR}/etc/rc.d/functions.d/sysinit" ]; then
+        echo "ERROR: You must install the larch version of 'initscripts'"
         fail=1
     fi
     if ${chrootx}grep /aufs.ko \
@@ -265,28 +269,6 @@ mklive ()
             cp -rf ${PROFILE}/rootoverlay/* ${LARCHBUILD}/tmp/overlay
         fi
 
-    fi
-
-    # Ensure a larch-enabled version of /etc/inittab is installed
-    if ! [ -f ${INSTLDIR}/etc/inittab.larchsave ]; then
-        echo "ERROR: No /etc/inittab.larchsave found"
-        return 1
-    fi
-    inittab=0
-    if ! [ -f ${LARCHBUILD}/tmp/overlay/etc/inittab ]; then
-        if grep "sysinit-larch" ${INSTLDIR}/etc/inittab &>/dev/null; then
-            inittab=1
-        else
-            mkdir -p ${LARCHBUILD}/tmp/overlay/etc
-            cp ${INSTLDIR}/etc/inittab.larchsave ${LARCHBUILD}/tmp/overlay/etc/inittab
-        fi
-    fi
-    if [ ${inittab} -eq 0 ] && \
-            ! grep "sysinit-larch" ${LARCHBUILD}/tmp/overlay/etc/inittab &>/dev/null; then
-        sed -i 's|^rc::sysinit.*|rc::sysinit:/etc/rc.sysinit-larch|' \
-                ${LARCHBUILD}/tmp/overlay/etc/inittab
-        sed -i 's|^rh:06.*|rh:06:wait:/etc/rc.shutdown-larch|' \
-                ${LARCHBUILD}/tmp/overlay/etc/inittab
     fi
 
     # Generate customized /etc/rc.conf
