Reorganization of overlays in larch (buildlive) - added 'rootoverlay' handling. Files copied from boot medium now in larch/copy. Tweaks to xmini profile.

diff --git a/trunk/larch-live/session-save/shutdown2 b/trunk/larch-live/session-save/shutdown2
--- a/trunk/larch-live/session-save/shutdown2
+++ b/trunk/larch-live/session-save/shutdown2
@@ -129,6 +129,18 @@ session_save ()
             mount ${savedev} ${savemount}
         fi
 
+        # Save autologin user
+        mkdir -p ${savepath}/larch
+        if [ -f /tmp/newuser ]; then
+            cat /tmp/newuser >${savepath}/larch/autologin
+        else
+            :> ${savepath}/larch/autologin
+        fi
+        if [ $? -ne 0 ]; then
+            echo "ERROR: Couldn't save autologin user"
+            return 1
+        fi
+
         rm -rf ${savepath}/overlay.ovl~
 
         if [ -z "${merge}" ]; then
