New overlay merging algorithm (needs testing)

diff --git a/branches/larch51dev/larch-live/session-save/merge_overlay b/branches/larch51dev/larch-live/session-save/merge_overlay
--- a/branches/larch51dev/larch-live/session-save/merge_overlay
+++ b/branches/larch51dev/larch-live/session-save/merge_overlay
@@ -21,10 +21,7 @@
 #    51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 #
 #----------------------------------------------------------------------------
-# 2008.02.20
-
-# The new overlay will be built in memory (main tmpfs?)
-merge_base=/.livesys
+# 2008.02.21
 
 # test if the script is started by root user. If not, exit
 if [ $UID -ne 0 ]; then
@@ -47,26 +44,16 @@ if [ -f ${overlaypath}/larch/merge-adjust ] ; then
     . ${overlaypath}/larch/merge-adjust
 fi
 
-merge_union=${merge_base}/merge_union
-merge_dir=${merge_base}/merge_dir
+merge_union=/.livesys/merge_union
+new_overlay=/.livesys/new_overlay/overlay
 rm -rf ${merge_union}
 mkdir -p ${merge_union}
-rm -rf ${merge_dir}
-mkdir -p ${merge_dir}
-if [ "${merge_base}" = "/.livesys" ]; then
-    # if swap available, use a new tmpfs
-    mktmpfs="$( cat /proc/swaps )"
-    if [ -z "${mktmpfs}" ]; then
-        swapon -a
-        mktmpfs="$( cat /proc/swaps )"
-    fi
-    if [ -n "${mktmpfs}" ]; then
-        mount -t tmpfs tmpfs ${merge_dir}
-    fi
-fi
+rm -rf ${new_overlay}
+mkdir -p ${new_overlay}
 
 utype="$( cat /.livesys/utype )"
 if [ "${utype}" = "unionfs" ]; then
+    sqfmnt="ro"
     ovlmnt="ro"
     bropt="dirs="
     opq=".wh.__dir_opaque"
@@ -75,68 +62,86 @@ else
         echo "ERROR: bad union type (${utype}), trying aufs"
         utype="aufs"
     fi
+    sqfmnt="rr"
     ovlmnt="ro+wh"
     bropt="br:"
     opq=".wh..wh..opq"
 elif
 
-layers="/.livesys/overlay=${ovlmnt}:/.livesys/mods=${ovlmnt}"
+layers="${new_overlay}=rw:/.livesys/overlay=${ovlmnt}:/.livesys/mods=${sqfmnt}"
 mount -t ${utype} -o ${bropt}${layers} ${utype} ${merge_union}
 
-echo "Copying 'overlay' files to ${merge_dir}"
+# Remove stuff from var
+rm -rf ${merge_union}/var/log
+rm -rf ${merge_union}/var/tmp
+rm -rf ${merge_union}/var/cache/pacman/pkg
+# Add missing stuff in /var
+mkdir -p ${merge_union}/var/log/old
+:>${merge_union}/var/log/wtmp
+:>${merge_union}/var/log/btmp
+:>${merge_union}/var/log/lastlog
+mkdir -m 1777 ${merge_union}/var/tmp
 
-# Function to restore whiteouts, where necessary, to the merged overlay
-whiteouts ()
-{
-    d="$1"
-    cd "${merge_dir/${d}}"
-    find . -type d | sed "s|^\./||" | while read n; do
-        if [ "${n}" = "." ]; then continue; fi
-
-        # Get all whiteout files (not directories) in the branches
-        for bdir in overlay mods; do
-            cd "/.livesys/${bdir}/${d}"
-            find . -maxdepth 1 -regex '\./\.wh\..*' -type f | while read w; do
-                wf="${w#\./\.wh\.}"
-                if [ -e "/.livesys/system/${d}/${wf}" ]; then
-                    cp -a "${w}" "${merge_dir/${d}}"
-                fi
-            done
-        done
-}
-
+echo "creating mods.sqf_"
 # Note that 'etc' is not included - mods.sqf has no /etc directory.
-# The following directories are ignored:
-#TODO!!!
-#      /var/log /var/tmp /var/cache/pacman/pkg
+savedirs=""
 for d in bin boot home lib mnt opt root sbin srv usr var; do
     if [ -d "${merge_union}/${d}" ]; then
-        cp -a "${merge_union}/${d}" "${merge_dir}"
-        whiteouts "${d}"
+        savedirs="${savedirs} ${d}"
+    fi
+done
+
+cd ${merge_union}
+mksquashfs "${savedirs}" "${overlaypath}/mods.tmp"
+if [ $? -ne 0 ]; then
+    echo "ERROR: Couldn't create ${overlaypath}/mods.sqf_"
+    rm -f "${overlaypath}/mods.tmp"
+    exit 1
+fi
+
+echo "creating overlay.ovl_"
+# Handle whiteouts and overlay
+for d in ${savedirs} etc; do
+    if [ -d "/.livesys/overlay/${d}" ]; then
+        cd "/.livesys/overlay/${d}"
+        find . -regex '.*/\.wh\.[^/]*' -type f | while read w; do
+            wb="$( basename "${w}" )"
+            wd="$( dirname "${w}" )"
+            # Copy whiteout using temporary destination name with '.x' prefix
+            cp -a "/.livesys/overlay/${d}/${wd#\./}/${wb}" \
+                    "${merge_union}/${d}/${wd#\./}/.x${wb}"
+        done
     fi
 done
 
 # Discard merge union
 umount ${merge_union}
 
-echo "creating mods.sqf_"
-mksquashfs "${merge_dir}" "${overlaypath}/mods.sqf_"
+# Rename whiteouts
+cd ${new_overlay}
+find . -regex '.*/\.x\.wh\.[^/]*' -type f | while read w; do
+    wb="$( basename "${w}" )"
+    wd="$( dirname "${w}" )"
+    mv "${w}" "${wd}/${wb#\.x}"
+done
+
+rm -rf ${new_overlay}/var/log
+rm -rf ${new_overlay}/var/tmp
+
+echo "Recompressing overlay"
+ovdirs=""
+for d in ${savedirs} etc; do
+    ovdirs="${ovdirs} overlay/${d}"
+done
+tar -cf - -C ${new_overlay}/.. ${ovdirs} | lzop > "${overlaypath}/overlay.tmp"
 if [ $? -ne 0 ]; then
-    echo "ERROR: Couldn't create ${overlaypath}/mods.sqf_"
-    rm -f ${overlaypath}/mods.sqf_
+    echo "ERROR: couldn't save overlay"
+    rm -f "${overlaypath}/overlay.tmp"
     exit 1
 fi
 
-if [ -n "${mktmpfs}" ]; then
-    umount ${merge_dir}
-fi
-rm -rf ${merge_dir}
+mv "${overlaypath}/overlay.tmp" "${overlaypath}/overlay.ovl_"
+mv "${overlaypath}/mods.tmp" "${overlaypath}/mods.sqf_"
 
-echo "creating overlay.ovl_"
-# Compress the overlay (with root dir 'overlay' retained)
-tar -cf - -C /.livesys overlay/etc | lzop > ${overlaypath}/overlay.ovl_
-if [ $? -ne 0 ]; then
-    echo "ERROR: couldn't create ${overlaypath}/overlay.ovl_"
-    rm -f ${overlaypath}/overlay.ovl_
-    exit 1
-fi
+rm -rf ${new_overlay}
+exit 0
