larchin (and -syscalls) version 6.1.0, for testing (don't update repo yet)
Fixed device without partition table bug (I hope).
Added framework for internationalization.

Warning: this code base is likely to be dropped. I am working on new, cleaner, code, but don't know when it will be ready. Probably for the next major larch revision.

diff --git a/branches/larch5.3/larchin-syscalls/syscalls/part-format b/branches/larch5.3/larchin-syscalls/syscalls/part-format
--- a/branches/larch5.3/larchin-syscalls/syscalls/part-format
+++ b/branches/larch5.3/larchin-syscalls/syscalls/part-format
@@ -4,9 +4,10 @@
 
 # Format a partition (argument $1), file-system type $2, options $3
 
-fmtext3 ()
+# For fs=ext3 and fs=ext4
+fmtext ()
 {
-    mke2fs -j $1
+    mkfs.${fs} $1
 
     if [ "$1" != "/" ]; then
         tune2fs -m 1 $1
@@ -23,21 +24,21 @@ fmtext3 ()
                     echo -n "Directory indexing failed"
                     return 1
                 fi ;;
-            C ) # disable boot-time checks
-                if ! tune2fs -c 0 -i 0 $1; then
-                    echo -n "Disabling boot-time checks failed"
-                    return 1
-                fi ;;
+#            C ) # disable boot-time checks
+#                if ! tune2fs -c 0 -i 0 $1; then
+#                    echo -n "Disabling boot-time checks failed"
+#                    return 1
+#                fi ;;
             F ) # full journalling
                 if ! tune2fs -O has_journal -o journal_data $1; then
                     echo -n "Full journalling failed"
                     return 1
                 fi ;;
             i ) ;;
-            c ) ;;
+#            c ) ;;
             f ) ;;
 
-            * ) echo -n "Unknown ext3 option: ${o}"
+            * ) echo -n "Unknown ${fs} option: ${o}"
                 return 1 ;;
         esac
     done
@@ -48,7 +49,8 @@ p=$1
 f=$2
 o=$3
 case ${f} in
-    ext3 ) fmtext3 ${p} ${o} ;;
+    ext4 ) fs="ext4" ; fmtext ${p} ${o} ;;
+    ext3 ) fs="ext3" ; fmtext ${p} ${o} ;;
     reiserfs ) mkreiserfs -q ${p} ;;
     ext2 ) mke2fs ${p} ;;
     jfs ) mkfs.jfs -q ${p} ;;
